defaults:
  - _self_
  - train: 35b_a3b

experiment:
  exp_name: outputs_qwen35_35b_a3b
  exp_dir: ./${experiment.exp_name}
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/megatron/train_qwen35.py
  runner:
    per_node_task: false
    no_shared_fs: false
    rdzv_backend: static
    nnodes: 1
    nproc_per_node: 16
  envs:
    LOGLEVEL: "DEBUG"
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    NVTE_APPLY_QK_LAYER_SCALING: 0
    NVTE_ALLOW_NONDETERMINISTIC_ALGO: 0
    HCCL_CONNECT_TIMEOUT: "7200"
    
    ASCEND_LAUNCH_BLOCKING: 0
    PYTORCH_NPU_ALLOC_CONF: "expandable_segments:True"
    MULTI_STREAM_MEMORY_REUSE: 2
    TASK_QUEUE_ENABLE: 2
    ACLNN_CACHE_LIMIT: 100000
    CPU_AFFINITY_CONF: 1
    NCCL_ALGO: Ring
    CUBLAS_WORKSPACE_CONFIG: ":4096:8"

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
